[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/live-tracking"
  to = "/live-tracking.html"
  status = 200

[[redirects]]
  from = "/private-journal"
  to = "/private-journal.html"
  status = 200

[[redirects]]
  from = "/guestbook"
  to = "/guestbook.html"
  status = 200

[dev]
  framework = "#static"
  autoLaunch = true
  targetPort = 3999
  port = 8888
